@startuml AssignTask
skinparam DefaultFontName Times New Roman
skinparam actorStyle awesome

actor User #DodgerBlue
participant Room #BlanchedAlmond
participant Simulation #LightSeaGreen
actor Robot #DarkRed
participant Task #SkyBlue

loop getValidRoom
User -> Room: getDirty
group validRoom
    Room -> Simulation: start creating task
    else Not Dirty / Invalid ID
        Room -> User: ask for new roomid
    end
end


loop findValidRobots
    Simulation -> Robot: getFree
    group ifAvailable
        Robot -> Simulation: put available Robots in task
    else notAvailable
        Simulation -> Simulation: move to the next robot
    end
end

group queryTask
    Simulation -> Simulation: check if enough robots are assigned to task
        group ifTaskValid
            Simulation -> Task: assign robots to task
            Task -> Task: create task
            Task -> Simulation: send task to simulation
        else
            Simulation -> User: return not enough Robots for task
        end
end

@enduml