@startuml
Robot -> Room: Go to Room
loop while cleanStatus == dirty
Simulation -> Simulation: increase timer
    alt if encounters failures
    Simulation -> Robot: checks failure
    Robot -> Robot -- : Fix(stay longer in room)
    else else
    Robot -> Robot: Clean
    end
end
@enduml
