@startuml
skinparam DefaultFontName Times New Roman
skinparam actorStyle awesome
Actor User
User << User >> #DodgerBlue

Actor Robot
Robot << Robot >> #Yellow

:User: -- (Use command line to control robots) #DodgerBlue
:User: -- (Report Robots' failures) #DodgerBlue
:Robot: -- (Use command line to control robots)
:Robot: -- (Report Robots' failures)
:Robot: -- (Return home after clean)
:User: -- (Check robot alerts if mulfunction) #DodgerBlue
@enduml