@startuml
skinparam DefaultFontName Times New Roman
skinparam actorStyle awesome
Actor User
User << User >> #DodgerBlue

Actor Robot
Robot << Robot >> #Yellow

Actor Simulation
Simulation << Simulation >> #Red

:User: -- (Make tasks) #DodgerBlue
:Simulation: -- (Make tasks) #Red
:Simulation: -- (Simulation Control) #Red
:Robot: -- (Simulation Control)
:Simulation: -- (Simulate Robots' failures) #Red
:Robot: -- (Simulate Robots' failures)
:Robot: -- (Return home after clean)
:User: -- (Check robot alerts if mulfunction) #DodgerBlue
@enduml