@startuml usecase3
skinparam DefaultFontName Times New Roman
skinparam actorStyle awesome
Actor User
User << User >> #DodgerBlue

Actor Building_manager
Building_manager << Building_manager >> #Yellow


package Building {
    usecase "Set rooms that can not be cleaned" as (set_location) #LightGrey
}

package Rooms {
    usecase "Picks room to be cleaned " as (robot_tasks) #LightGrey
}

:User: -- (robot_tasks) #DodgerBlue
:Building_manager: -- (set_location) #DodgerBlue
@enduml
