@startuml
skinparam DefaultFontName Times New Roman
skinparam actorStyle awesome
Actor User
User << User >> #DodgerBlue

Actor Building_manager
Building_manager << Building_manager >> #Yellow

Actor Fleet_Manager
Fleet_Manager << Fleet_Manager >> #IndianRed

package Building {
    usecase "Set locations to be cleaned" as (set_location) #LightGrey
}

package Robots {
    usecase "Send robots to perfom tasks " as (robot_tasks) #LightGrey
    usecase "Take control of the robots" as (control_robots) #LightGrey
}

:User: -- (robot_tasks) #DodgerBlue
:Building_manager: -- (set_location) #DodgerBlue
:Fleet_Manager: -- (control_robots)#DodgerBlue
@enduml